language: node_js
node_js: stable
cache:
  yarn: true
  npm: true
  directories:
    - node_modules
install:
  - npm install
script: npm run build
after_script:
  - cd ./dist
  - cp index.html 404.html
  - echo "pro.abckey.com" > CNAME
  - git init
  - git config  user.name "${U_NAME}"
  - git config  user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
branches:
  only:
    - master
