name: GitHub Actions Build and Deploy Project
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm run build
      - name: deploy to target directory
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
          repo: ibwei/abckey-pro
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_PAT: ${{secrets.MY_DEPLOY_KEY}}
