name: GitHub Actions Build and Deploy Project
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm run build
      - name: Upload to other gitpages
        run: |
          cd dist
          git init
          git config  user.name ibwei
          git config  user.email bawei3600@gmail.com
          git add .
          git commit -m "Automatically update from travis-ci"
          git push --quiet --force  `https://02e5aad907f73fc59b0fb1cec827172cbbc63846@github.com/ibwei/abckey-pro.git` master:gh-pages
